name       : rocksdb
version    : 6.19.3
release    : 3
source     :
    - https://github.com/facebook/rocksdb/archive/refs/tags/v6.19.3.tar.gz : 5c19ffefea2bbe4c275d0c60194220865f508f371c64f42e802b4a85f065af5b
homepage   : https://rocksdb.org/
license    :
    - Apache-2.0
    - BSD-3-Clause
component  : programming.library
summary    : A library that provides an embeddable, persistent key-value store for fast storage
description: |
    RocksDB is a library that forms the core building block for a fast key-value server, especially suited for storing data on flash drives. It has a Log-Structured-Merge-Database (LSM) design with flexible tradeoffs between Write-Amplification-Factor (WAF), Read-Amplification-Factor (RAF) and Space-Amplification-Factor (SAF). It has multi-threaded compactions, making it especially suitable for storing multiple terabytes of data in a single database.
builddeps  :
    - pkgconfig(gflags)
    - pkgconfig(liblz4)
    - pkgconfig(libzstd)
    - bzip2-devel
    - snappy-devel
rundeps    :
    - devel :
        - bzip2-devel
        - gflags-devel
        - lz4-devel
        - snappy-devel
        - zstd-devel
setup      : |
    %patch -p1 < $pkgfiles/disable-static.patch
    %cmake_ninja \
        -DROCKSDB_BUILD_SHARED=ON \
        -DWITH_BZ2=ON \
        -DWITH_SNAPPY=ON \
        -DWITH_LZ4=ON \
        -DWITH_ZLIB=ON \
        -DWITH_ZSTD=ON
build      : |
    %ninja_build
    %make gen-pc PREFIX=/usr LIBDIR=/usr/lib64
install    : |
    %ninja_install
    install -Dm00644 rocksdb.pc $installdir/usr/lib64/pkgconfig/rocksdb.pc
